build:
  nodes:
    analysis:
      environment:
        node: '16.14.0'
      dependencies:
        before:
          - npm install
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

filter:
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/

tools:
  external_code_coverage:
    timeout: 600
