# GitHub Action for Laravel with MySQL
# https://github.com/shivammathur/setup-php/blob/master/examples/laravel-mysql.yml
name: tests

on: [push, pull_request]

jobs:
  mysql_57:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - MySQL 5.7

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ngodingbang_laravel_stisla_starter
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          tools: composer:v2

      - name: Start mysql service
        run: sudo systemctl start mysql

      - name: Set minimum PHP 8.1 versions
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require league/commonmark:^2.0.2 ramsey/collection:^1.2 brick/math:^0.9.3 --no-interaction --no-update
        if: matrix.php >= 8.1

      - name: Install composer dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy environment file
        run: php -r "file_exists('.env') || copy('.env.github.mysql', '.env');"

      - name: Generate app key
        run: php artisan key:generate

      - name: Clear config
        run: php artisan config:clear

      - name: Run migration
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Install front-end dependencies
        run: npm install

      - name: Execute tests
        run: vendor/bin/pest --verbose
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

  mysql_8:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - MySQL 8.0.28

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ngodingbang_laravel_stisla_starter
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          tools: composer:v2

      - name: Start mysql service
        run: sudo systemctl start mysql

      - name: Set minimum PHP 8.1 versions
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require league/commonmark:^2.0.2 ramsey/collection:^1.2 brick/math:^0.9.3 --no-interaction --no-update
        if: matrix.php >= 8.1

      - name: Install composer dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy environment file
        run: php -r "file_exists('.env') || copy('.env.github.mysql', '.env');"

      - name: Generate app key
        run: php artisan key:generate

      - name: Clear config
        run: php artisan config:clear

      - name: Run migration
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Install front-end dependencies
        run: npm install

      - name: Execute tests
        run: vendor/bin/pest --verbose
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

  postgresql:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - PostgreSQL 12.6

    runs-on: ubuntu-latest

    needs: [mysql_57, mysql_8]

    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ngodingbang_laravel_stisla_starter
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: Set minimum PHP 8.1 versions
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require league/commonmark:^2.0.2 ramsey/collection:^1.2 brick/math:^0.9.3 --no-interaction --no-update
        if: matrix.php >= 8.1

      - name: Install composer dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy environment file
        run: php -r "file_exists('.env') || copy('.env.github.postgresql', '.env');"

      - name: Generate app key
        run: php artisan key:generate

      - name: Clear config
        run: php artisan config:clear

      - name: Run migration
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Install front-end dependencies
        run: npm install

      - name: Execute tests
        run: |
          mkdir -p build/logs
          vendor/bin/pest --verbose --coverage-clover build/logs/clover.xml
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
